# Generated by Django 3.2.7 on 2021-09-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20210922_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
