# Generated by Django 3.2.7 on 2021-09-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_remove_post_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
