# Generated by Django 3.2.7 on 2021-09-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
